services:
  web:
    image: ruby:latest
    container_name: rails_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      bash -c "
      if [ ! -f Gemfile ]; then
        gem install rails &&
        rails new . --force --database=postgresql
      fi &&
      bundle install &&
      rm -f tmp/pids/server.pid &&
      rails server -b 0.0.0.0"
    
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: